# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run  Cypress tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  chrome:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

       # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false

      # Install Ionic CLI globally
      - run: npm install @ionic/cli -g

      # Run all Cypress tests
      - name: Tests on Chrome
        uses: cypress-io/github-action@v1
        with:
          install: false
          start: ionic serve --https
          wait-on: 'https://localhost:8100'
          browser: chrome
          headless: true