name: Browser Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  netlify:
    runs-on: ubuntu-16.04
    outputs:
      url: ${{steps.netlify.outputs.url}}
    steps:
      - uses: kamranayub/wait-for-netlify-action@v2.0.3
        id: netlify
        with:
          site_name: "carved-rock-order-tracker-pwa"
          max_timeout: 300
        env:
          NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}